package: cdek
generate:
  models: true
  client: true
  embedded-spec: false
output: pkg/cdek/client.go
output-options:
  skip-prune: true
  user-templates:
    imports.tmpl: templates/imports.tmpl
compatibility:
  always-prefix-enum-values: true
